In [1]:
### K Means Clustering

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs

In [5]:
from sklearn.cluster import KMeans
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [6]:
Kmeans = KMeans(n_clusters=2, random_state=0, n_init='auto').fit(X)

In [8]:
Kmeans.labels_

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [9]:
Kmeans.predict([[0,0], [12,3]])

array([1, 0], dtype=int32)

In [2]:
### Hierarchial clustering

In [3]:
### dbscan clustering