In [1]:
import numpy as np






In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# range works in case of only integers.
list(range(0.5, 10))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
# In numpy we can do this by using np.arange() :
np.arange(0.5, 10)

In [ ]:
# It also goes in negative axis and have step method too:

np.arange(5, -6, -2) # (start, end(excluded), step)

----------------------------------------------------------------------------------------------

In [ ]:
# we can devide specific range of numbers into required chunks:
np.linspace(1,10,20) # We are deviding numbers from 1 to 10 into 20 similar chunks

In [ ]:
np.linspace(1,10,20, retstep = True) # shows rate of steping to divide in 20

---------------------------------------------------------------------------------------------------------

In [ ]:
# we can get log of our linespace using logspace: ( base is 10 by default)
np.logspace(2,12, 24)

--------------------------------------------------------------------------------------------------------------


In [ ]:
# We can create array of zero and one as it's element:

np.zeros(2)

In [ ]:
np.zeros((2,3))

In [ ]:
# same for ones:

np.ones(4)

In [ ]:
np.ones((2, 3))

In [ ]:
# we can multiply our array with other number if we want array of that specific number: 

np.ones((2,3)) * 5

-----------------------------------------------------------------------------------------

In [ ]:
# create a empty array : 

In [4]:
np.empty((2,3))

array([[4.64208624e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

--------------------------------------------------------------------------------


In [5]:
# Identity matics:  diagonal value are 1 and everything else is zero.

a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# find info : 
a.shape

(3, 3)

In [7]:
import numpy as np

m = np.eye(4)

print(m.ndim)
print(m.size)
print(m.shape)

2
16
(4, 4)


--------------------------------------------------------------------------------

### Seed for random data generation: 

In [8]:
np.random.rand(3,4) 

array([[0.10542628, 0.10429763, 0.63628628, 0.77014728],
       [0.74220371, 0.67740897, 0.92501645, 0.9467007 ],
       [0.89117385, 0.04715026, 0.08342716, 0.25633705]])

In [9]:
np.random.rand(3,4) 

array([[0.23839197, 0.39366082, 0.17849093, 0.63690577],
       [0.26677262, 0.56709268, 0.86113733, 0.08730659],
       [0.68841303, 0.52082902, 0.48855733, 0.78152348]])

In [10]:
np.random.rand(3,4) 


array([[0.79704944, 0.08287952, 0.51806205, 0.50146574],
       [0.21956093, 0.89600064, 0.63903486, 0.75033219],
       [0.36896702, 0.92292872, 0.39390219, 0.08852879]])

data never stays same if we run it again we will get different set of data each time, we can use seed method to lock random data.

In [11]:
np.random.seed(47) # seed can be any intger, acts as reference point
np.random.rand(3,4)

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

In [12]:
np.random.seed(47) 
np.random.rand(3,4)

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

--------------------------------------------------------------------------------

### Accessing the required data from array:

In [13]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a[1][1]

1.0

In [15]:
a[1:3,1:3] # [rows,columns]

array([[1., 0.],
       [0., 1.]])

In [16]:
a[[0,2],[0,2]]

array([1., 1.])

In [17]:
a[[0,2],[0,2,3]] # rows and columns must be same

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
a[[1,2],3] # acceptable as we are asking for only one column and multiple rows ... vice versa

In [ ]:
a[2, [1,2]]

---------------------------------------------------------

### Mathematical operations 

In [18]:
# lets create two arrays 
import numpy as np
m1 = np.random.randint(1,9, (3,3))
m2 = np.random.randint(1,9, (3,3))

In [19]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [20]:
 m2 # in here also even we run same expression still we got different array... magic of randomness

array([[1, 3, 7],
       [8, 2, 5],
       [4, 5, 6]])

In [21]:
m1*m2 # normal multiplication: element vise

array([[ 2,  9, 14],
       [16, 12,  5],
       [ 8, 25, 18]])

In [22]:
m1@m2 # matrix multiplication: 

array([[34, 22, 41],
       [54, 23, 50],
       [54, 31, 57]])

if m1 have `m*n` shape and m2 have p*q shape then ...` n = p`in order to do matrix multiplication , and for normal multiplication `m = P` and `n = q`.

other mathematical funtions: 

In [24]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [23]:
pow(m1, 3) #power

array([[  8,  27,   8],
       [  8, 216,   1],
       [  8, 125,  27]])

In [25]:
np.sqrt(m1) # squar root

array([[1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 2.44948974, 1.        ],
       [1.41421356, 2.23606798, 1.73205081]])

In [26]:
np.log10(m1) # log with base 10 

array([[0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.77815125, 0.        ],
       [0.30103   , 0.69897   , 0.47712125]])

In [27]:
np.exp(m1) exponent

array([[  7.3890561 ,  20.08553692,   7.3890561 ],
       [  7.3890561 , 403.42879349,   2.71828183],
       [  7.3890561 , 148.4131591 ,  20.08553692]])

In [28]:
m1**2 # square

array([[ 4,  9,  4],
       [ 4, 36,  1],
       [ 4, 25,  9]])

--------------------------------------------------------------------------------------