# NUMPY: Numerical Python

In [1]:
import numpy as np

In [5]:
l =[1, 2, 3, 4, 5, 6, 7, 8, 9]
type(l)

list

In [7]:
a = np.array(l)
type(a)

numpy.ndarray

In [8]:
# We can check how many dimensions our array haves:
a.ndim 

1

In [10]:
# Using nested lists we can create 2, 3, and ...n dim array:
l2 = [[2,3,4],[4,3,2]] # gives two dimensional array
a2 = np.array(l2)
print(a2.ndim)

2


In [11]:
l3 = [[[2,3,4],[4,3,2]],[[2,3,4],[4,3,2]],[[2,3,4],[4,3,2]]]
a3 = np.array(l3)
print(a3.ndim)

3


So we can say that `n` dimensional array is made up of `n-1` dimensional arrays as it's elements.

### Matrix:

In [13]:
m = np.matrix(l) # matrix is is at least two dim
m

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
m

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
np.asanyarray(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.asanyarray(m)

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Matrix is subclass of array superclass.

### Shallow Copy vs Deep Copy:

In [18]:
# Shallow Copy: 

shallow_copy = a2
print(shallow_copy)

[[2 3 4]
 [4 3 2]]


In [19]:
shallow_copy[1][1] = 20
print(shallow_copy)

[[ 2  3  4]
 [ 4 20  2]]


In [20]:
a2

array([[ 2,  3,  4],
       [ 4, 20,  2]])

By directly assigning array to new variable we are creating a shallow copy which points to the same memory location, hence when we make any changes in `shallow_copy` those changes will be reflected in the `a2`

In [21]:
# Deep Copy: 

deep_copy = np.copy(a2)
print(deep_copy)

[[ 2  3  4]
 [ 4 20  2]]


In [22]:
deep_copy[1][1] = 200
print(deep_copy)

[[  2   3   4]
 [  4 200   2]]


In [23]:
a2 # no changes are made in original array

array([[ 2,  3,  4],
       [ 4, 20,  2]])

In this case, we are creating new memory location. 

### Generating arrays Using different methods:

In [24]:
np.fromfunction(lambda i,j: i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.random.rand(3,2) # (m,n) = m: rows, n: columns

array([[0.8984732 , 0.49198838],
       [0.24468766, 0.62757015],
       [0.33019868, 0.02929786]])

In [27]:
np.random.rand(4,3,2) # (m, n, l) = m: no of slices, n: no of rows, l: no of columns

array([[[0.61383975, 0.76949315],
        [0.74827178, 0.91551406],
        [0.38430789, 0.43062455]],

       [[0.57095688, 0.30036763],
        [0.58828689, 0.10550431],
        [0.35429286, 0.32809273]],

       [[0.06706002, 0.88971687],
        [0.9797851 , 0.0249451 ],
        [0.55742568, 0.1914919 ]],

       [[0.16202862, 0.31509068],
        [0.60863354, 0.43363531],
        [0.51812662, 0.87395089]]])

In [41]:
np.random.randn(2,3,2)

array([[[ 0.21762453,  0.1376404 ],
        [-2.43647928,  0.02311844],
        [-0.29186057,  0.86222712]],

       [[ 0.36932178, -0.7361735 ],
        [-0.21662525, -0.99581123],
        [-0.59771115,  1.09484466]]])

In [34]:
normal_dist = np.random.randn(2,3) # all of data is normally distributed: mean = 0, standard deviation = 1
normal_dist

array([[ 0.88594548, -0.41312265, -0.11835335],
       [ 1.0025275 , -0.57948219,  0.54338351]])

We can convert above 2D array into a data frame also using pandas

In [38]:
import pandas as pd

In [37]:
pd.DataFrame(normal_dist) # works with 2D array only

0         1         2
0  0.885945 -0.413123 -0.118353
1  1.002528 -0.579482  0.543384

By using reshape function we can transform array from one dim to another


In [43]:
my_array = np.random.rand(3, 3, 3)
print(my_array)
print(my_array.ndim)

[[[0.61612884 0.14755457 0.65592423]
  [0.52506644 0.86693437 0.81381122]
  [0.51079683 0.39914397 0.22449067]]

 [[0.6896879  0.58460977 0.02182388]
  [0.8920217  0.68466536 0.86190987]
  [0.47929372 0.48110218 0.11593367]]

 [[0.14048988 0.81887395 0.87256796]
  [0.10117599 0.87107675 0.80272449]
  [0.77189273 0.14951409 0.04116156]]]
3


The main key is `3*3*3 == 9*3`

In [45]:
new_array = my_array.reshape(9,3) # K
print(new_array.ndim)
print(new_array)

2
[[0.61612884 0.14755457 0.65592423]
 [0.52506644 0.86693437 0.81381122]
 [0.51079683 0.39914397 0.22449067]
 [0.6896879  0.58460977 0.02182388]
 [0.8920217  0.68466536 0.86190987]
 [0.47929372 0.48110218 0.11593367]
 [0.14048988 0.81887395 0.87256796]
 [0.10117599 0.87107675 0.80272449]
 [0.77189273 0.14951409 0.04116156]]


In [46]:
pd.DataFrame(new_array)

0         1         2
0  0.616129  0.147555  0.655924
1  0.525066  0.866934  0.813811
2  0.510797  0.399144  0.224491
3  0.689688  0.584610  0.021824
4  0.892022  0.684665  0.861910
5  0.479294  0.481102  0.115934
6  0.140490  0.818874  0.872568
7  0.101176  0.871077  0.802724
8  0.771893  0.149514  0.041162

-1 as filler

In [47]:
new_array = my_array.reshape(3, -1) # -1 acts as filler which gets replaced by appropriate number 
new_array

array([[0.61612884, 0.14755457, 0.65592423, 0.52506644, 0.86693437,
        0.81381122, 0.51079683, 0.39914397, 0.22449067],
       [0.6896879 , 0.58460977, 0.02182388, 0.8920217 , 0.68466536,
        0.86190987, 0.47929372, 0.48110218, 0.11593367],
       [0.14048988, 0.81887395, 0.87256796, 0.10117599, 0.87107675,
        0.80272449, 0.77189273, 0.14951409, 0.04116156]])