In [4]:
import numpy as np


In [5]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
# range works in case of only integers.
list(range(0.5, 10))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
# In numpy we can do this by using np.arange():
np.arange(0.5, 10, step = 2)

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [8]:
# It also goes in negative axis and have step method too:

np.arange(5, -6, -2) # (start, end(excluded), step)

array([ 5,  3,  1, -1, -3, -5])

----------------------------------------------------------------------------------------------

In [9]:
# we can devide specific range of numbers into required chunks:
np.linspace(1,10,20) # We are deviding numbers from 1 to 10 into 20 similar chunks

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [10]:
np.linspace(1,10,20, retstep = True) # shows rate of steping to divide in 20

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

---------------------------------------------------------------------------------------------------------

In [11]:
# we can get log of our linespace using logspace: (base is 10 by default)
np.logspace(2,12, 24)

array([1.00000000e+02, 2.72133877e+02, 7.40568469e+02, 2.01533769e+03,
       5.48441658e+03, 1.49249555e+04, 4.06158599e+04, 1.10529514e+05,
       3.00788252e+05, 8.18546731e+05, 2.22754295e+06, 6.06189899e+06,
       1.64964807e+07, 4.48925126e+07, 1.22167735e+08, 3.32459793e+08,
       9.04735724e+08, 2.46209240e+09, 6.70018750e+09, 1.82334800e+10,
       4.96194760e+10, 1.35031404e+11, 3.67466194e+11, 1.00000000e+12])

--------------------------------------------------------------------------------------------------------------


In [12]:
# We can create array of zero and one as it's element:

np.zeros(2)

array([0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# same for ones:

np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# we can multiply our array with other number if we want array of that specific number: 

np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

-----------------------------------------------------------------------------------------

In [17]:
# create a empty array : 

In [18]:
np.empty((2,3))

array([[5., 5., 5.],
       [5., 5., 5.]])

--------------------------------------------------------------------------------


In [19]:
# Identity matics:  diagonal value are 1 and everything else is zero.

a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# find info : 
a.shape

(3, 3)

In [21]:
import numpy as np

m = np.eye(4)

print(m.ndim)
print(m.size)
print(m.shape)

2
16
(4, 4)


--------------------------------------------------------------------------------

### Seed for random data generation: 

In [22]:
np.random.rand(3,4) 

array([[0.63367653, 0.38669463, 0.18978878, 0.19557901],
       [0.89424567, 0.10181314, 0.72071214, 0.22301759],
       [0.00662238, 0.32059264, 0.16037619, 0.73774096]])

In [23]:
np.random.rand(3,4) 

array([[0.30454656, 0.61839093, 0.25399608, 0.08389948],
       [0.76975027, 0.16623623, 0.70385735, 0.81961576],
       [0.57098701, 0.31885432, 0.17554477, 0.37381136]])

In [24]:
np.random.rand(3,4) 


array([[0.75828087, 0.03828462, 0.20628223, 0.0526816 ],
       [0.92482923, 0.29122059, 0.00574201, 0.18981727],
       [0.52027395, 0.31984288, 0.59941665, 0.55934746]])

data never stays same if we run it again we will get different set of data each time, we can use seed method to lock random data.

In [25]:
np.random.seed(47) # seed can be any intger, acts as reference point
np.random.rand(3,4)

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

In [26]:
np.random.seed(47) 
np.random.rand(3,4)

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

--------------------------------------------------------------------------------

### Accessing the required data from array:

In [36]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [37]:
a[1][1]

5

In [38]:
a[1:3,1:3] # [rows,columns]

array([[5, 6],
       [8, 9]])

In [40]:
a[[0,2],[0,2]]

array([1, 9])

a[[0, 2], [0, 2]]: This selects elements from the array at the following positions:

From row 0, column 0: a[0, 0] (element 1)

From row 2, column 2: a[2, 2] (element 9)

In [33]:
a[[0,2],[0,2,3]] # rows and columns must be same

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [42]:
a[[1,2],2] # acceptable as we are asking for only one column and multiple rows ... vice versa

array([6, 9])

In [43]:
a[2, [1,2]]

array([8, 9])

---------------------------------------------------------

### Mathematical operations 

In [44]:
# lets create two arrays 
import numpy as np
m1 = np.random.randint(1,9, (3,3))
m2 = np.random.randint(1,9, (3,3))

In [45]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [46]:
 m2 # in here also even we run same expression still we got different array... magic of randomness

array([[1, 3, 7],
       [8, 2, 5],
       [4, 5, 6]])

In [47]:
m1*m2 # normal multiplication: element vise

array([[ 2,  9, 14],
       [16, 12,  5],
       [ 8, 25, 18]])

In [ ]:
m1@m2 # matrix multiplication: 

array([[34, 22, 41],
       [54, 23, 50],
       [54, 31, 57]])

if m1 have `m*n` shape and m2 have p*q shape then ...` n = p`in order to do matrix multiplication , and for normal multiplication `m = P` and `n = q`.

other mathematical funtions: 

In [ ]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [ ]:
pow(m1, 3) #power

array([[  8,  27,   8],
       [  8, 216,   1],
       [  8, 125,  27]])

In [48]:
np.sqrt(m1) # squar root

array([[1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 2.44948974, 1.        ],
       [1.41421356, 2.23606798, 1.73205081]])

In [49]:
np.log10(m1) # log with base 10 

array([[0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.77815125, 0.        ],
       [0.30103   , 0.69897   , 0.47712125]])

In [ ]:
np.exp(m1) exponent

array([[  7.3890561 ,  20.08553692,   7.3890561 ],
       [  7.3890561 , 403.42879349,   2.71828183],
       [  7.3890561 , 148.4131591 ,  20.08553692]])

In [ ]:
m1**2 # square

array([[ 4,  9,  4],
       [ 4, 36,  1],
       [ 4, 25,  9]])

--------------------------------------------------------------------------------------