In [8]:
import numpy as np


In [1]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
# range works in case of only integers.
list(range(0.5, 10))

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
# In numpy we can do this by using np.arange():
np.arange(0.5, 10, step = 2)

array([0.5, 2.5, 4.5, 6.5, 8.5])

In [60]:
# It also goes in negative axis and have step method too:

np.arange(start=5,stop= -6,step= -2) # (start, end(excluded), step)

array([ 5,  3,  1, -1, -3, -5])

----------------------------------------------------------------------------------------------

In [14]:
# we can devide specific range of numbers into required chunks:
np.linspace(1,10,20) # We are deviding numbers from 1 to 10 into 20 similar chunks

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [59]:
np.linspace(start=1,stop= 10,num=20, retstep = True) # shows rate of steping to divide in 20

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

---------------------------------------------------------------------------------------------------------

In [16]:
# we can get log of our linespace using logspace: (base is 10 by default)
np.logspace(2,12, 24)

array([1.00000000e+02, 2.72133877e+02, 7.40568469e+02, 2.01533769e+03,
       5.48441658e+03, 1.49249555e+04, 4.06158599e+04, 1.10529514e+05,
       3.00788252e+05, 8.18546731e+05, 2.22754295e+06, 6.06189899e+06,
       1.64964807e+07, 4.48925126e+07, 1.22167735e+08, 3.32459793e+08,
       9.04735724e+08, 2.46209240e+09, 6.70018750e+09, 1.82334800e+10,
       4.96194760e+10, 1.35031404e+11, 3.67466194e+11, 1.00000000e+12])

--------------------------------------------------------------------------------------------------------------


In [17]:
# We can create array of zero and one as it's element:

np.zeros(2)

array([0., 0.])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# same for ones:

np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# we can multiply our array with other number if we want array of that specific number: 

np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

-----------------------------------------------------------------------------------------

In [22]:
# create a empty array : 

In [64]:
np.empty((6,3))

array([[ 1.30643886e-316,  0.00000000e+000,  1.66830158e-316],
       [ 6.90079650e-310, -6.95893117e-196,  4.75284782e-037],
       [-6.27685266e-167, -2.69659898e-157,  2.26176373e-309],
       [ 8.03735577e-301,  4.32690536e-297, -1.43182480e-133],
       [ 3.60350125e-306,  6.48601720e-310,  6.90079603e-310],
       [ 1.63041663e-322,  1.85146793e-316,  6.90079650e-310]])

--------------------------------------------------------------------------------


In [66]:
# Identity matics:  diagonal value are 1 and everything else is zero.

a = np.eye(7)
a

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
# find info : 
a.shape

(3, 3)

In [26]:
import numpy as np

m = np.eye(4)

print(m.ndim)
print(m.size)
print(m.shape)

2
16
(4, 4)


--------------------------------------------------------------------------------

### Seed for random data generation: 

In [27]:
np.random.rand(3,4) 

array([[0.53128164, 0.65486589, 0.19160926, 0.592744  ],
       [0.60905537, 0.42671302, 0.04761534, 0.90964786],
       [0.65222734, 0.31855282, 0.85279544, 0.89129794]])

In [28]:
np.random.rand(3,4) 

array([[0.12191645, 0.39783034, 0.39886613, 0.34385899],
       [0.97687343, 0.04493904, 0.26461147, 0.72019154],
       [0.3277368 , 0.97926328, 0.53223285, 0.51277475]])

In [29]:
np.random.rand(3,4) 


array([[0.35475197, 0.17782592, 0.62897635, 0.118709  ],
       [0.83103366, 0.12639911, 0.60170873, 0.18660662],
       [0.52146919, 0.61832398, 0.85105545, 0.34433416]])

data never stays same if we run it again we will get different set of data each time, we can use seed method to lock random data.

In [30]:
np.random.seed(47) # seed can be any intger, acts as reference point
np.random.rand(3,4) 

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

In [31]:
np.random.seed(47) 
np.random.rand(3,4)

array([[0.11348847, 0.97448309, 0.72873463, 0.35146781],
       [0.70760514, 0.7996046 , 0.64556185, 0.41459961],
       [0.70603101, 0.24664938, 0.25599243, 0.02401135]])

--------------------------------------------------------------------------------

### Accessing the required data from array:

In [32]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [33]:
a[1][1]

5

In [34]:
a[1:3,1:3] # [rows,columns]

array([[5, 6],
       [8, 9]])

In [35]:
a[[0,2],[0,2]]

array([1, 9])

a[[0, 2], [0, 2]]: This selects elements from the array at the following positions:

From row 0, column 0: a[0, 0] (element 1)

From row 2, column 2: a[2, 2] (element 9)

In [36]:
a[[0,2],[0,2,3]] # rows and columns must be same

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [37]:
a[[1,2],2] # acceptable as we are asking for only one column and multiple rows ... vice versa

array([6, 9])

In [38]:
a[2, [1,2]]

array([8, 9])

---------------------------------------------------------

### Mathematical operations 

In [69]:
np.random.randint(low=1,high=9, size=(3,3))

array([[7, 5, 5],
       [8, 3, 4],
       [2, 3, 5]])

In [39]:
# lets create two arrays 
import numpy as np
m1 = np.random.randint(1,9, (3,3))
m2 = np.random.randint(1,9, (3,3))

In [40]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [41]:
 m2 # in here also even we run same expression still we got different array... magic of randomness

array([[1, 3, 7],
       [8, 2, 5],
       [4, 5, 6]])

In [42]:
m1*m2 # normal multiplication: element vise

array([[ 2,  9, 14],
       [16, 12,  5],
       [ 8, 25, 18]])

In [43]:
m1@m2 # matrix multiplication: 

array([[34, 22, 41],
       [54, 23, 50],
       [54, 31, 57]])

if m1 have `m*n` shape and m2 have p*q shape then ...` n = p`in order to do matrix multiplication , and for normal multiplication `m = P` and `n = q`.

other mathematical funtions: 

In [44]:
m1

array([[2, 3, 2],
       [2, 6, 1],
       [2, 5, 3]])

In [45]:
pow(m1, 3) #power

array([[  8,  27,   8],
       [  8, 216,   1],
       [  8, 125,  27]])

In [46]:
np.sqrt(m1) # squar root

array([[1.41421356, 1.73205081, 1.41421356],
       [1.41421356, 2.44948974, 1.        ],
       [1.41421356, 2.23606798, 1.73205081]])

In [47]:
np.log10(m1) # log with base 10 

array([[0.30103   , 0.47712125, 0.30103   ],
       [0.30103   , 0.77815125, 0.        ],
       [0.30103   , 0.69897   , 0.47712125]])

In [48]:
np.exp(m1) #exponent

array([[  7.3890561 ,  20.08553692,   7.3890561 ],
       [  7.3890561 , 403.42879349,   2.71828183],
       [  7.3890561 , 148.4131591 ,  20.08553692]])

In [49]:
m1**2 # square

array([[ 4,  9,  4],
       [ 4, 36,  1],
       [ 4, 25,  9]])

--------------------------------------------------------------------------------------

### Broadcasting

Extra 

In [55]:
array1 = np.array([1, 2, 3, 4])
print(array1)
print(array1.shape)

[1 2 3 4]
(4,)


In [51]:

array2 = np.array([5,6,7,8]).reshape(4, 1)
print(array2)
print(array2.shape)

[[5]
 [6]
 [7]
 [8]]
(4, 1)


In [52]:

print(array1)
print(array2)
print("mat mul-----------")
print(np.matmul(array1, array2))

[1 2 3 4]
[[5]
 [6]
 [7]
 [8]]
mat mul-----------
[70]


In [53]:

print(array1)
print(array2.T)
print("mat mul -----------------------")
print(np.matmul(array2.T, array1))


[1 2 3 4]
[[5 6 7 8]]
mat mul -----------------------
[70]


In [54]:
import numpy as np

# Create two arrays with 3 numbers in each
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Display the shape of each array
print("Array 1 Shape:", array1.shape)
print("Array 2 Shape:", array2.shape)

# Perform matrix multiplication
result = np.matmul(array1, array2)

# Alternatively, you can use the @ operator
# result = array1 @ array2

# Display the result
print("Matrix Multiplication Result:", result)


Array 1 Shape: (3,)
Array 2 Shape: (3,)
Matrix Multiplication Result: 32
